apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: heybot
  namespace: argocd
spec:
  destination:
    namespace: default
    server: https://kubernetes.default.svc
  source:
    repoURL: 'https://github.com/thaotll/heybot'
    targetRevision: HEAD
    path: 'k8s'
  project: default
