# analysis-pv.yaml
apiVersion: v1
kind: PersistentVolume
metadata:
  name: analysis-pv
  labels:
    type: local-analysis
spec:
  storageClassName: manual
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/data/heybot-analysis"
  persistentVolumeReclaimPolicy: Retain
