---
# Source: heybot/templates/analyzer-job.yaml
apiVersion: batch/v1
kind: Job
metadata:
  name: heybot-analyzer
  labels:
    helm.sh/chart: heybot-0.1.0
    app.kubernetes.io/name: heybot
    app.kubernetes.io/instance: heybot
    app.kubernetes.io/version: "1.16.0"
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/component: analyzer
  annotations:
    # Annotation, um ArgoCD zu signalisieren, den Job bei jeder Synchronisierung neu zu erstellen,
    # wenn sich die Konfiguration (z.B. Image-Tag) ge채ndert hat.
    argocd.argoproj.io/hook: Sync
    argocd.argoproj.io/hook-delete-policy: BeforeHookCreation
spec:
  template:
    metadata:
      labels:
        app.kubernetes.io/name: heybot
        app.kubernetes.io/instance: heybot
        app.kubernetes.io/component: analyzer
    spec:
      restartPolicy: Never # Job soll nicht neu starten, wenn er fehlschl채gt, sondern als fehlgeschlagen gelten
      containers:
        - name: analyzer
          image: "ghcr.io/thaotll/heybot-with-trivy-output:6f2f7048b8b42f5db0d54c74c69a6ef7f885804d"
          imagePullPolicy: Always
          command: ["/app/start.sh"] # Stellt sicher, dass main.py ausgef체hrt wird
          env:
            - name: CURRENT_COMMIT_ID
              value: "6f2f7048b8b42f5db0d54c74c69a6ef7f885804d" # Der Image-Tag ist Commit-ID
            - name: MODEL_HUMOR_PATH
              value: /app/model_humor.txt 
            # Secrets sollten 체ber Kubernetes Secrets eingebunden werden
            - name: DISCORD_WEBHOOK_URL
              valueFrom:
                secretKeyRef:
                  name: heybot-secrets
                  key: DISCORD_WEBHOOK_URL
            - name: DEEPSEEK_API_KEY
              valueFrom:
                secretKeyRef:
                  name: heybot-secrets
                  key: DEEPSEEK_API_KEY
          volumeMounts:
            - name: analysis-volume
              mountPath: /app/analysis 
            - name: humor-files
              subPath: model_humor.txt 
      volumes:
        - name: analysis-volume
          persistentVolumeClaim:
            claimName: analysis-pvc 
        - name: humor-files
          secret:
            secretName: heybot-humor-secret
      serviceAccountName: heybot
