apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: analysis-pvc
  namespace: default
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
  volumeName: analysis-pv
  storageClassName: ""
