apiVersion: apps/v1
kind: Deployment
metadata:
  name: heybot-app
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: heybot
  template:
    metadata:
      labels:
        app: heybot
    spec:
      containers:
        - name: heybot
          image: ghcr.io/thaotll/heybot-with-trivy-output:latest
          command: [ "sh", "-c", "python3 /app/main.py && python3 /app/bazinga_cve_bot.py" ]
          envFrom:
            - secretRef:
                name: heybot-secrets
          volumeMounts:
            - name: analysis-volume
              mountPath: /app/analysis
      volumes:
        - name: analysis-volume
          persistentVolumeClaim:
            claimName: analysis-pvc
      imagePullSecrets:
        - name: ghcr-secret
