---
# Source: heybot/templates/deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: heybot
  labels:
    helm.sh/chart: heybot-0.1.0
    app.kubernetes.io/name: heybot
    app.kubernetes.io/instance: heybot
    app.kubernetes.io/version: "1.16.0"
    app.kubernetes.io/managed-by: Helm
spec:
  replicas: 
  selector:
    matchLabels:
      app.kubernetes.io/name: heybot
      app.kubernetes.io/instance: heybot
  template:
    metadata:
      labels:
        helm.sh/chart: heybot-0.1.0
        app.kubernetes.io/name: heybot
        app.kubernetes.io/instance: heybot
        app.kubernetes.io/version: "1.16.0"
        app.kubernetes.io/managed-by: Helm
    spec:
      serviceAccountName: heybot
      containers:
        - name: heybot
          image: "ghcr.io/thaotll/heybot-with-trivy-output:6f2f7048b8b42f5db0d54c74c69a6ef7f885804d"
          imagePullPolicy: Always
          ports:
            - name: http
              containerPort: 80
              protocol: TCP
