apiVersion: apps/v1
kind: Deployment
metadata:
  name: heybot-app
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: heybot
  template:
    metadata:
      labels:
        app: heybot
      annotations:
        commit-id: "6d8c15cca608ea8a840c330a64287ef26aa7b824"
    spec:
      containers:
        - name: heybot
          image: ghcr.io/thaotll/heybot-with-trivy-output:6d8c15cca608ea8a840c330a64287ef26aa7b824
          imagePullPolicy: Always
          command: ["/app/start.sh"]
          env:
            - name: CURRENT_COMMIT_ID
              valueFrom:
                fieldRef:
                  fieldPath: metadata.annotations['commit-id']
          envFrom:
            - secretRef:
                name: heybot-secrets
          volumeMounts:
            - name: analysis-volume
              mountPath: /app/analysis
      volumes:
        - name: analysis-volume
          persistentVolumeClaim:
            claimName: analysis-pvc
      imagePullSecrets:
        - name: ghcr-secret
