---
# Source: heybot/templates/deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: heybot
  labels:
    helm.sh/chart: heybot-0.1.0
    app.kubernetes.io/name: heybot
    app.kubernetes.io/instance: heybot
    app.kubernetes.io/version: "1.16.0"
    app.kubernetes.io/managed-by: Helm
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: heybot
      app.kubernetes.io/instance: heybot
  template:
    metadata:
      labels:
        helm.sh/chart: heybot-0.1.0
        app.kubernetes.io/name: heybot
        app.kubernetes.io/instance: heybot
        app.kubernetes.io/version: "1.16.0"
        app.kubernetes.io/managed-by: Helm
    spec:
      serviceAccountName: heybot
      containers:
        - name: heybot
          image: "ghcr.io/thaotll/heybot-with-trivy-output:a68f3d37aaf2409d0df7a04a3722299731804bdf"
          imagePullPolicy: Always
          ports:
            - name: http
              containerPort: 80
              protocol: TCP
          env:
            - name: MODEL_HUMOR_PATH
              value: /app/secrets/model_humor.txt
          volumeMounts:
            - mountPath: /app/secrets
              name: model-humor-volume
              readOnly: true
      volumes:
        - name: model-humor-volume
          secret:
            secretName: heybot-humor-secret
