image:
  repository: ghcr.io/thaotll/heybot-with-trivy-output
  tag: latest
  pullPolicy: Always

serviceAccount:
  create: true
  automount: true
  annotations: {}
  # name: "spezifischer-name" # Überschreibt den generierten Namen, falls nötig

# Konfiguration für das Haupt-Deployment
  replicaCount: 1
  autoscaling:
    enabled: false
    minReplicas: 1
    maxReplicas: 10
    targetCPUUtilizationPercentage: 80

# Konfiguration für den Analyzer Job
analyzer:
  pvcName: analysis-pvc 
  secrets:
    discordWebhook:
      name: "heybot-secrets" 
      key: "DISCORD_WEBHOOK_URL"
    deepseekApiKey:
      name: "heybot-secrets"
      key: "DEEPSEEK_API_KEY"
    humorSecretName: 
      name: "heybot-humor-secret"
      key: "model_humor.txt"

service:
  port: 80
  targetPort: 3000
  nodePort: 31000
  type: NodePort

# Zusätzliche Konfigurationen für Pods (gelten für Deployment und Job, falls nicht überschrieben)
podAnnotations: {}
podLabels: {}

imagePullSecrets: []
# - name: mein-ghcr-secret

# Ressourcenanforderungen und -limits (gelten für Deployment und Job)
resources: {}
  # limits:
  #   cpu: 100m
  #   memory: 128Mi
  # requests:
  #   cpu: 100m
  #   memory: 128Mi

nodeSelector: {}
tolerations: []
affinity: {}