image:
  repository: ghcr.io/thaotll/heybot-with-trivy-output
  tag: latest
  pullPolicy: Always

replicaCount: 1

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 10
  targetCPUUtilizationPercentage: 80

serviceAccount:
  create: true
  automount: true
  annotations: {}
  # name: "spezifischer-name" # Überschreibt den generierten Namen, falls nötig

service:
  port: 80
  targetPort: 3000
  nodePort: 31000
  type: NodePort

podAnnotations: {}
podLabels: {}

imagePullSecrets: []
# - name: ghcr-secret

resources: {}
  # limits:
  #   cpu: 100m
  #   memory: 128Mi
  # requests:
  #   cpu: 100m
  #   memory: 128Mi

nodeSelector: {}
tolerations: []
affinity: {}

ingress:
  enabled: false
  className: ""
  annotations: {}
  hosts:
    - host: heybot.local
      paths:
        - path: /
          pathType: ImplementationSpecific
  tls: []
  #  - secretName: chart-example-tls
  #    hosts:
  #      - chart-example.local

# Umgebungsvariablen für heybot (insb. MODEL_HUMOR_PATH)
env:
  - name: MODEL_HUMOR_PATH
    value: "/app/secrets/model_humor.txt"
  - name: DEEPSEEK_API_KEY
    valueFrom:
      secretKeyRef:
        name: heybot-secrets
        key: deepseek-api-key
  - name: DISCORD_WEBHOOK_URL
      secretKeyRef:
        name: heybot-secrets
        key: discord-webhook-url

# VolumeMounts für das Secret
volumeMounts:
  - name: model-humor-volume
    mountPath: /app/secrets
    readOnly: true

# Volume-Definition für das Secret
volumes:
  - name: model-humor-volume
    secret:
      secretName: heybot-humor-secret
