name: Docker Image Scan

on: [push]

env:
  USER: "thaotll"
  KUBECONFIG_BASE64: ${{ secrets.KUBECONFIG_BASE64 }}

jobs:
  trivy_scan:
    runs-on: ubuntu-latest

    steps:
      # Checkout the code.
      - name: Checkout code
        uses: actions/checkout@v2

      # Login to GitHub Container Registry
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}  # Use the GitHub username (actor)
          password: ${{ secrets.GHCR_TOKEN }}  # Use the secret token

      # Build the Docker image
      - name: Build the hello-docker Docker image
        run: |
          docker build -t ghcr.io/$USER/heybot:latest .

      # Install Trivy (Specific version v0.60.1)
      - name: Install Trivy
        uses: aquasecurity/setup-trivy@v0.2.0
        with:
          version: latest # Specify the desired version

      # Scan the Docker image for vulnerabilities
      - name: Scan Docker image for vulnerabilities
        run: |
          trivy image --severity HIGH,CRITICAL --format json --output trivy_output.json ghcr.io/$USER/heybot:latest
      
      # Build the new Docker image with trivy_output.json
      - name: Build the new Docker image with trivy_output.json
        run: |
          docker build -t ghcr.io/$USER/heybot-with-trivy-output:latest -f Dockerfile.trivy-analysis .
      
      # Push the Docker image to GitHub Container Registry
      - name: Push the Docker image to GitHub Container Registry
        run: |
          docker push ghcr.io/$USER/heybot-with-trivy-output:latest

      # Debug Secret
      - name: Debug Secret
        run: |
          if [ -z "${KUBECONFIG_BASE64}" ]; then
            echo "Secret ist leer oder nicht verfügbar!"
            exit 1
          else
            echo "Secret ist gesetzt (Wert wird nicht angezeigt)."
          fi
        env:
          KUBECONFIG_BASE64: ${{ secrets.KUBECONFIG_BASE64 }}

      # Set up kubeconfig
      - name: Set up kubeconfig
        run: |
          mkdir -p $HOME/.kube
          ls -la $HOME/.kube
          echo "${KUBECONFIG_BASE64}" | base64 -d > $HOME/.kube/config
          ls -la $HOME/.kube
        env:
          KUBECONFIG_BASE64: ${{ secrets.KUBECONFIG_BASE64 }}
